name: IntegrationTests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IT_DIR: ${{github.workspace}}/integration_tests

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        case: [cpm, fetch_git, fetch_release]

    steps:
    - uses: actions/checkout@v4

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.26.1'

    - name: Configure
      working-directory: ${{env.IT_DIR}}/${{matrix.case}}
      run: |
        mkdir _build
        cd _build
        cmake ..
      shell: cmd

    - name: Build
      working-directory: ${{env.IT_DIR}}/${{matrix.case}}/_build
      run: |
        cmake --build . --config Debug
      shell: cmd
