name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{github.workspace}}/vsbuild

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.26.1'

    - name: Check cmake version
      run: cmake --version

    - name: Configure CMake
      run: |
        mkdir "${{env.BUILD_DIR}}"
        cd "${{env.BUILD_DIR}}"
        cmake ..
      shell: cmd

    - name: Build
      working-directory: ${{env.BUILD_DIR}}
      run: |
        cmake --build . --config Debug
        cmake --build . --config Release
      shell: cmd

    - name: Test
      working-directory: ${{env.BUILD_DIR}}
      run: |
        ctest -C Debug
        ctest -C Release
      shell: cmd
